# Generated by Django 2.0.5 on 2018-07-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0012_auto_20180715_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.Permit'),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='zoning',
            field=models.CharField(choices=[('R-1', 'R-1 - single-family district'), ('R-7A', 'R-7A - manufactured home district'), ('R-2', 'R-2 - single-family district'), ('R-3', 'R-3 - single-family district'), ('PID', 'PID - planned industrial district'), ('MF-18', 'MF-18 - multifamily district'), ('FP', 'FP - floodplain district'), ('R-5', 'R-5 - urban residence district'), ('PRD', 'PRD - planned residential district'), ('DOD', 'DOD - design overlay district'), ('O-1', 'O-1 - quiet office district'), ('M', 'M - mining district'), ('O-2', 'O-2 - office and institutional district'), ('C-3', 'C-3 - general commercial district'), ('C-4', 'C-4 - open display commercial district'), ('OS', 'OS - open space district'), ('R-4', 'R-4 - two-family district'), ('R-6', 'R-6 - high-rise apartment district'), ('PD', 'PD - industrial district'), ('O-3', 'O-3 - general office district'), ('MF-24', 'MF-24 - multifamily district'), ('I-2', 'I-2 - light industrial district'), ('C-1', 'C-1 - neighborhood commercial district'), ('C-2', 'C-2 - shopping center district'), ('I-3', 'I-3 - heavy industrial district'), ('AF', 'AF - agriculture and forestry district'), ('R-7', 'R-7 - manufactured home park district'), ('I-1', 'I-1 - industrial park district'), ('MF-12', 'MF-12 - multifamily district'), ('R-4A', 'R-4A - low density residential district'), ('PCD', 'PCD - planned commercial district'), ('MF-6', 'MF-6 - multifamily district'), ('POD', 'POD - planned office district'), ('UU', 'UU - urban use district.'), ('PR', 'PR - Park and recreation district')], max_length=20),
        ),
    ]
